version: "3.8"

services:

  fastapi:
    build: .
    command: bash -c "pip install -r req.txt  && uvicorn main:app --port 8000"
    volumes:
      - .:/application
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: "storehouse_postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - storehouse_data:/var/lib/postgresql/data

volumes:
  storehouse_data:
