version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: "storehouse_postgres"
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - storehouse_data:/var/lib/postgresql/data

volumes:
  storehouse_data:
