"""empty message

Revision ID: 17c9c8a9d250
Revises: d1433ac376a7
Create Date: 2023-10-06 15:21:28.258656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c9c8a9d250'
down_revision: Union[str, None] = 'd1433ac376a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pallet', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'pallet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pallet', type_='foreignkey')
    op.drop_column('pallet', 'user_id')
    # ### end Alembic commands ###
