"""d

Revision ID: 40734d6fb923
Revises: 0a2443131756
Create Date: 2023-10-01 14:55:48.965618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40734d6fb923'
down_revision: Union[str, None] = '0a2443131756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'location', ['shelving', 'row', 'column'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='unique')
    # ### end Alembic commands ###
