"""empty message

Revision ID: cf953a835937
Revises: 17c9c8a9d250
Create Date: 2023-10-06 15:23:51.165529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf953a835937"
down_revision: Union[str, None] = "17c9c8a9d250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pallet", sa.Column("location_id", sa.UUID(), nullable=False))
    op.add_column("pallet", sa.Column("supplier_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "pallet", "location", ["location_id"], ["id"])
    op.create_foreign_key(None, "pallet", "supplier", ["supplier_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pallet", type_="foreignkey")
    op.drop_constraint(None, "pallet", type_="foreignkey")
    op.drop_column("pallet", "supplier_id")
    op.drop_column("pallet", "location_id")
    # ### end Alembic commands ###
